name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, 8.0, 8.1, 8.2]
        include:
          - php: 7.3
            phpunit: 9.3
          - php: 7.4
            phpunit: 9.3
          - php: 8.0
            phpunit: 9.3
          - php: 8.1
            phpunit: 9.3
          - php: 8.2
            phpunit: 10.5

    name: PHP:${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require phpunit/phpunit:^${{ matrix.phpunit }} --dev && composer install --prefer-dist --no-interaction --no-suggest

      - name: Run Unit tests
        run: vendor/bin/phpunit --coverage-clover=tests/logs/clover.xml
