name: Test

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Pint

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Pint
        run: vendor/bin/pint

      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix code style (Laravel Pint)

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11.*, 12.*, 13.*]
        exclude:
          - php: 8.2
            laravel: 13.*

    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-

      - name: Install Laravel ${{ matrix.laravel }}
        run: composer require "illuminate/support:${{ matrix.laravel }}" "illuminate/database:${{ matrix.laravel }}" "illuminate/filesystem:${{ matrix.laravel }}" "illuminate/console:${{ matrix.laravel }}" --no-update

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Unit tests
        run: vendor/bin/phpunit
